In [111]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [112]:
dataset=pd.read_excel("IPEDS_data.xlsx")
dataset.head()

,ID number,Name,year,ZIP code,Highest degree offered,County name,Longitude location of institution,Latitude location of institution,Religious affiliation,Offers Less than one year certificate,...,Percent of freshmen receiving federal grant aid,Percent of freshmen receiving Pell grants,Percent of freshmen receiving other federal grant aid,Percent of freshmen receiving state/local grant aid,Percent of freshmen receiving institutional grant aid,Percent of freshmen receiving student loan aid,Percent of freshmen receiving federal student loans,Percent of freshmen receiving other loan aid,Endowment assets (year end) per FTE enrollment (GASB),Endowment assets (year end) per FTE enrollment (FASB)
0,100654,Alabama A & M University,2013,35762,Doctor's degree - research/scholarship,Madison County,-86.568502,34.783368,Not applicable,Implied no,...,81.0,81.0,7.0,1.0,32.0,89.0,89.0,1.0,NaN,NaN
1,100663,University of Alabama at Birmingham,2013,35294-0110,Doctor's degree - research/scholarship and pro...,Jefferson County,-86.809170,33.502230,Not applicable,Implied no,...,36.0,36.0,10.0,0.0,60.0,56.0,55.0,5.0,24136.0,NaN
2,100690,Amridge University,2013,36117-3553,Doctor's degree - research/scholarship and pro...,Montgomery County,-86.174010,32.362609,Churches of Christ,Implied no,...,90.0,90.0,0.0,40.0,90.0,100.0,100.0,0.0,NaN,302.0
3,100706,University of Alabama in Huntsville,2013,35899,Doctor's degree - research/scholarship and pro...,Madison County,-86.638420,34.722818,Not applicable,Yes,...,31.0,31.0,4.0,1.0,63.0,46.0,46.0,3.0,11502.0,NaN
4,100724,Alabama State University,2013,36104-0271,Doctor's degree - research/scholarship and pro...,Montgomery County,-86.295677,32.364317,Not applicable,Implied no,...,76.0,76.0,13.0,11.0,34.0,81.0,81.0,0.0,13202.0,NaN

In [113]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1534 entries, 0 to 1533
Columns: 145 entries, ID number to Endowment assets (year end) per FTE enrollment (FASB)
dtypes: float64(116), int64(2), object(27)
memory usage: 1.7+ MB

In [114]:
dataset.isnull().sum()

ID number                                                   0
Name                                                        0
year                                                        0
ZIP code                                                    0
Highest degree offered                                      0
                                                         ...
Percent of freshmen receiving student loan aid             42
Percent of freshmen receiving federal student loans        42
Percent of freshmen receiving other loan aid               42
Endowment assets (year end) per FTE enrollment (GASB)    1018
Endowment assets (year end) per FTE enrollment (FASB)     574
Length: 145, dtype: int64

In [115]:
dataset.describe()

,ID number,year,Longitude location of institution,Latitude location of institution,Applicants total,Admissions total,Enrolled total,Percent of freshmen submitting SAT scores,Percent of freshmen submitting ACT scores,SAT Critical Reading 25th percentile score,...,Percent of freshmen receiving federal grant aid,Percent of freshmen receiving Pell grants,Percent of freshmen receiving other federal grant aid,Percent of freshmen receiving state/local grant aid,Percent of freshmen receiving institutional grant aid,Percent of freshmen receiving student loan aid,Percent of freshmen receiving federal student loans,Percent of freshmen receiving other loan aid,Endowment assets (year end) per FTE enrollment (GASB),Endowment assets (year end) per FTE enrollment (FASB)
count,1534.000000,1534.0,1534.000000,1534.000000,1377.000000,1377.000000,1377.000000,1257.000000,1259.000000,1169.000000,...,1492.00000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,1492.000000,516.000000,9.600000e+02
mean,189091.037810,2013.0,-88.342338,38.729993,6391.193174,3554.880174,1043.046478,53.927605,53.085782,470.340462,...,41.47185,40.764075,15.418901,35.384718,70.335121,64.959786,64.180295,7.553619,9459.463178,6.503032e+04
std,58641.915456,0.0,14.838804,4.832832,8787.469171,4309.457606,1285.165519,34.385164,31.658662,68.368390,...,18.88068,18.560557,14.091423,21.897744,29.463324,19.143070,19.337354,7.706674,19398.443224,1.773784e+05
min,100654.000000,2013.0,-158.062444,19.701854,0.000000,0.000000,0.000000,0.000000,0.000000,310.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.000000,4.200000e+01
25%,153148.500000,2013.0,-94.576341,35.348340,1488.000000,950.000000,287.000000,16.000000,26.000000,430.000000,...,28.00000,27.000000,6.000000,18.000000,48.000000,54.000000,53.000000,2.000000,2080.000000,8.391000e+03
50%,186508.000000,2013.0,-84.514218,39.946096,3350.000000,2056.000000,538.000000,65.000000,49.000000,460.000000,...,40.00000,39.000000,12.000000,34.000000,78.000000,68.000000,67.000000,6.000000,4283.000000,1.870400e+04
75%,215730.000000,2013.0,-77.207136,41.984929,7016.000000,4203.000000,1246.000000,86.000000,87.000000,500.000000,...,51.25000,51.000000,20.250000,50.000000,98.000000,79.000000,78.000000,11.000000,8715.500000,4.505250e+04
max,456490.000000,2013.0,-67.456534,64.857053,72676.000000,35815.000000,10241.000000,100.000000,100.000000,720.000000,...,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,83.000000,213079.000000,2.505435e+06

In [116]:
dataset["Applicants total"].fillna(dataset["Applicants total"].median(), inplace=True)
dataset["Admissions total"].fillna(dataset["Admissions total"].median(), inplace=True)
dataset["Enrolled total"].fillna(dataset["Enrolled total"].median(), inplace=True)
dataset["Percent of freshmen submitting SAT scores"].fillna(dataset["Percent of freshmen submitting SAT scores"].median(), inplace=True)
dataset["Percent of freshmen submitting ACT scores"].fillna(dataset["Percent of freshmen submitting ACT scores"].median(), inplace=True)
dataset["SAT Critical Reading 25th percentile score"].fillna(dataset["SAT Critical Reading 25th percentile score"].median(), inplace=True)
dataset["SAT Critical Reading 75th percentile score"].fillna(dataset["SAT Critical Reading 75th percentile score"].median(), inplace=True)
dataset["SAT Math 25th percentile score"].fillna(dataset["SAT Math 25th percentile score"].median(), inplace=True)
dataset["SAT Math 75th percentile score"].fillna(dataset["SAT Math 75th percentile score"].median(), inplace=True)
dataset["SAT Writing 25th percentile score"].fillna(dataset["SAT Writing 25th percentile score"].median(), inplace=True)
dataset["SAT Writing 75th percentile score"].fillna(dataset["SAT Writing 75th percentile score"].median(), inplace=True)
dataset["ACT Composite 25th percentile score"].fillna(dataset["ACT Composite 25th percentile score"].median(), inplace=True)
dataset["ACT Composite 75th percentile score"].fillna(dataset["ACT Composite 75th percentile score"].median(), inplace=True)
dataset["Estimated enrollment, total"].fillna(dataset["Estimated enrollment, total"].median(), inplace=True)
dataset["Estimated enrollment, full time"].fillna(dataset["Estimated enrollment, full time"].median(), inplace=True)
dataset["Estimated enrollment, part time"].fillna(dataset["Estimated enrollment, part time"].median(), inplace=True)
dataset["Estimated undergraduate enrollment, total"].fillna(dataset["Estimated undergraduate enrollment, total"].median(), inplace=True)
dataset["Estimated undergraduate enrollment, full time"].fillna(dataset["Estimated undergraduate enrollment, full time"].median(), inplace=True)
dataset["Estimated undergraduate enrollment, part time"].fillna(dataset["Estimated undergraduate enrollment, part time"].median(), inplace=True)
dataset["Estimated freshman undergraduate enrollment, total"].fillna(dataset["Estimated freshman undergraduate enrollment, total"].median(), inplace=True)
dataset["Estimated freshman enrollment, full time"].fillna(dataset["Estimated freshman enrollment, full time"].median(), inplace=True)
dataset["Estimated freshman enrollment, part time"].fillna(dataset["Estimated freshman enrollment, part time"].median(), inplace=True)
dataset["Estimated graduate enrollment, total"].fillna(dataset["Estimated graduate enrollment, total"].median(), inplace=True)
dataset["Estimated graduate enrollment, full time"].fillna(dataset["Estimated graduate enrollment, full time"].median(), inplace=True)
dataset["Estimated graduate enrollment, part time"].fillna(dataset["Estimated graduate enrollment, part time"].median(), inplace=True)
dataset["Associate's degrees awarded"].fillna(dataset["Associate's degrees awarded"].median(), inplace=True)
dataset["Bachelor's degrees awarded"].fillna(dataset["Bachelor's degrees awarded"].median(), inplace=True)
dataset["Master's degrees awarded"].fillna(dataset["Master's degrees awarded"].median(), inplace=True)
dataset["Doctor's degrese - research/scholarship awarded"].fillna(dataset["Doctor's degrese - research/scholarship awarded"].median(), inplace=True)
dataset["Doctor's degrees - professional practice awarded"].fillna(dataset["Doctor's degrees - professional practice awarded"].median(), inplace=True)
dataset["Doctor's degrees - other awarded"].fillna(dataset["Doctor's degrees - other awarded"].median(), inplace=True)
dataset["Certificates of less than 1-year awarded"].fillna(dataset["Certificates of less than 1-year awarded"].median(), inplace=True)
dataset["Certificates of 1 but less than 2-years awarded"].fillna(dataset["Certificates of 1 but less than 2-years awarded"].median(), inplace=True)
dataset["Certificates of 2 but less than 4-years awarded"].fillna(dataset["Certificates of 2 but less than 4-years awarded"].median(), inplace=True)
dataset["Postbaccalaureate certificates awarded"].fillna(dataset["Postbaccalaureate certificates awarded"].median(), inplace=True)
dataset["Post-master's certificates awarded"].fillna(dataset["Post-master's certificates awarded"].median(), inplace=True)
dataset["Number of students receiving an Associate's degree"].fillna(dataset["Number of students receiving an Associate's degree"].median(), inplace=True)
dataset["Number of students receiving a Bachelor's degree"].fillna(dataset["Number of students receiving a Bachelor's degree"].median(), inplace=True)
dataset["Number of students receiving a Master's degree"].fillna(dataset["Number of students receiving a Master's degree"].median(), inplace=True)
dataset["Number of students receiving a Doctor's degree"].fillna(dataset["Number of students receiving a Doctor's degree"].median(), inplace=True)
dataset["Number of students receiving a certificate of less than 1-year"].fillna(dataset["Number of students receiving a certificate of less than 1-year"].median(), inplace=True)
dataset["Number of students receiving a certificate of 1 but less than 4-years"].fillna(dataset["Number of students receiving a certificate of 1 but less than 4-years"].median(), inplace=True)
dataset["Number of students receiving a Postbaccalaureate or Post-master's certificate"].fillna(dataset["Number of students receiving a Postbaccalaureate or Post-master's certificate"].median(), inplace=True)
dataset["Percent admitted - total"].fillna(dataset["Percent admitted - total"].median(), inplace=True)
dataset["Admissions yield - total"].fillna(dataset["Admissions yield - total"].median(), inplace=True)
dataset["Tuition and fees, 2010-11"].fillna(dataset["Tuition and fees, 2010-11"].median(), inplace=True)
dataset["Tuition and fees, 2011-12"].fillna(dataset["Tuition and fees, 2011-12"].median(), inplace=True)
dataset["Tuition and fees, 2012-13"].fillna(dataset["Tuition and fees, 2012-13"].median(), inplace=True)
dataset["Tuition and fees, 2013-14"].fillna(dataset["Tuition and fees, 2013-14"].median(), inplace=True)
dataset["Total price for in-state students living on campus 2013-14"].fillna(dataset["Total price for in-state students living on campus 2013-14"].median(), inplace=True)
dataset["Total price for out-of-state students living on campus 2013-14"].fillna(dataset["Total price for out-of-state students living on campus 2013-14"].median(), inplace=True)
dataset["Total  enrollment"].fillna(dataset["Total  enrollment"].median(), inplace=True)
dataset["Full-time enrollment"].fillna(dataset["Full-time enrollment"].median(), inplace=True)
dataset["Part-time enrollment"].fillna(dataset["Part-time enrollment"].median(), inplace=True)
dataset["Undergraduate enrollment"].fillna(dataset["Undergraduate enrollment"].median(), inplace=True)
dataset["Graduate enrollment"].fillna(dataset["Graduate enrollment"].median(), inplace=True)
dataset["Full-time undergraduate enrollment"].fillna(dataset["Full-time undergraduate enrollment"].median(), inplace=True)
dataset["Part-time undergraduate enrollment"].fillna(dataset["Part-time undergraduate enrollment"].median(), inplace=True)
dataset["Percent of total enrollment that are American Indian or Alaska Native"].fillna(dataset["Percent of total enrollment that are American Indian or Alaska Native"].median(), inplace=True)
dataset["Percent of total enrollment that are Asian"].fillna(dataset["Percent of total enrollment that are Asian"].median(), inplace=True)
dataset["Percent of total enrollment that are Black or African American"].fillna(dataset["Percent of total enrollment that are Black or African American"].median(), inplace=True)
dataset["Percent of total enrollment that are Hispanic/Latino"].fillna(dataset["Percent of total enrollment that are Hispanic/Latino"].median(), inplace=True)
dataset["Percent of total enrollment that are Native Hawaiian or Other Pacific Islander"].fillna(dataset["Percent of total enrollment that are Native Hawaiian or Other Pacific Islander"].median(), inplace=True)
dataset["Percent of total enrollment that are White"].fillna(dataset["Percent of total enrollment that are White"].median(), inplace=True)
dataset["Percent of total enrollment that are two or more races"].fillna(dataset["Percent of total enrollment that are two or more races"].median(), inplace=True)
dataset["Percent of total enrollment that are Race/ethnicity unknown"].fillna(dataset["Percent of total enrollment that are Race/ethnicity unknown"].median(), inplace=True)
dataset["Percent of total enrollment that are Nonresident Alien"].fillna(dataset["Percent of total enrollment that are Nonresident Alien"].median(), inplace=True)
dataset["Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander"].fillna(dataset["Percent of total enrollment that are Asian/Native Hawaiian/Pacific Islander"].median(), inplace=True)
dataset["Percent of total enrollment that are women"].fillna(dataset["Percent of total enrollment that are women"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are American Indian or Alaska Native"].fillna(dataset["Percent of undergraduate enrollment that are American Indian or Alaska Native"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Asian"].fillna(dataset["Percent of undergraduate enrollment that are Asian"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Black or African American"].fillna(dataset["Percent of undergraduate enrollment that are Black or African American"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Hispanic/Latino"].fillna(dataset["Percent of undergraduate enrollment that are Hispanic/Latino"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Native Hawaiian or Other Pacific Islander"].fillna(dataset["Percent of undergraduate enrollment that are Native Hawaiian or Other Pacific Islander"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are White"].fillna(dataset["Percent of undergraduate enrollment that are White"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are two or more races"].fillna(dataset["Percent of undergraduate enrollment that are two or more races"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Race/ethnicity unknown"].fillna(dataset["Percent of undergraduate enrollment that are Race/ethnicity unknown"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Nonresident Alien"].fillna(dataset["Percent of undergraduate enrollment that are Nonresident Alien"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander"].fillna(dataset["Percent of undergraduate enrollment that are Asian/Native Hawaiian/Pacific Islander"].median(), inplace=True)
dataset["Percent of undergraduate enrollment that are women"].fillna(dataset["Percent of undergraduate enrollment that are women"].median(), inplace=True)
dataset["Percent of graduate enrollment that are American Indian or Alaska Native"].fillna(dataset["Percent of graduate enrollment that are American Indian or Alaska Native"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Asian"].fillna(dataset["Percent of graduate enrollment that are Asian"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Black or African American"].fillna(dataset["Percent of graduate enrollment that are Black or African American"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Hispanic/Latino"].fillna(dataset["Percent of graduate enrollment that are Hispanic/Latino"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Native Hawaiian or Other Pacific Islander"].fillna(dataset["Percent of graduate enrollment that are Native Hawaiian or Other Pacific Islander"].median(), inplace=True)
dataset["Percent of graduate enrollment that are White"].fillna(dataset["Percent of graduate enrollment that are White"].median(), inplace=True)
dataset["Percent of graduate enrollment that are two or more races"].fillna(dataset["Percent of graduate enrollment that are two or more races"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Race/ethnicity unknown"].fillna(dataset["Percent of graduate enrollment that are Race/ethnicity unknown"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Nonresident Alien"].fillna(dataset["Percent of graduate enrollment that are Nonresident Alien"].median(), inplace=True)
dataset["Percent of graduate enrollment that are Asian/Native Hawaiian/Pacific Islander"].fillna(dataset["Percent of graduate enrollment that are Asian/Native Hawaiian/Pacific Islander"].median(), inplace=True)
dataset["Percent of graduate enrollment that are women"].fillna(dataset["Percent of graduate enrollment that are women"].median(), inplace=True)
dataset["Number of first-time undergraduates - in-state"].fillna(dataset["Number of first-time undergraduates - in-state"].median(), inplace=True)
dataset["Percent of first-time undergraduates - in-state"].fillna(dataset["Percent of first-time undergraduates - in-state"].median(), inplace=True)
dataset["Number of first-time undergraduates - out-of-state"].fillna(dataset["Number of first-time undergraduates - out-of-state"].median(), inplace=True)
dataset["Percent of first-time undergraduates - out-of-state"].fillna(dataset["Percent of first-time undergraduates - out-of-state"].median(), inplace=True)
dataset["Number of first-time undergraduates - foreign countries"].fillna(dataset["Number of first-time undergraduates - foreign countries"].median(), inplace=True)
dataset["Percent of first-time undergraduates - foreign countries"].fillna(dataset["Percent of first-time undergraduates - foreign countries"].median(), inplace=True)
dataset["Number of first-time undergraduates - residence unknown"].fillna(dataset["Number of first-time undergraduates - residence unknown"].median(), inplace=True)
dataset["Percent of first-time undergraduates - residence unknown"].fillna(dataset["Percent of first-time undergraduates - residence unknown"].median(), inplace=True)
dataset["Graduation rate - Bachelor degree within 4 years, total"].fillna(dataset["Graduation rate - Bachelor degree within 4 years, total"].median(), inplace=True)
dataset["Graduation rate - Bachelor degree within 5 years, total"].fillna(dataset["Graduation rate - Bachelor degree within 5 years, total"].median(), inplace=True)
dataset["Graduation rate - Bachelor degree within 6 years, total"].fillna(dataset["Graduation rate - Bachelor degree within 6 years, total"].median(), inplace=True)
dataset["Percent of freshmen receiving any financial aid"].fillna(dataset["Percent of freshmen receiving any financial aid"].median(), inplace=True)
dataset["Percent of freshmen receiving federal, state, local or institutional grant aid"].fillna(dataset["Percent of freshmen receiving federal, state, local or institutional grant aid"].median(), inplace=True)
dataset["Percent of freshmen  receiving federal grant aid"].fillna(dataset["Percent of freshmen  receiving federal grant aid"].median(), inplace=True)
dataset["Percent of freshmen receiving Pell grants"].fillna(dataset["Percent of freshmen receiving Pell grants"].median(), inplace=True)
dataset["Percent of freshmen receiving other federal grant aid"].fillna(dataset["Percent of freshmen receiving other federal grant aid"].median(), inplace=True)
dataset["Percent of freshmen receiving state/local grant aid"].fillna(dataset["Percent of freshmen receiving state/local grant aid"].median(), inplace=True)
dataset["Percent of freshmen receiving institutional grant aid"].fillna(dataset["Percent of freshmen receiving institutional grant aid"].median(), inplace=True)
dataset["Percent of freshmen receiving student loan aid"].fillna(dataset["Percent of freshmen receiving student loan aid"].median(), inplace=True)
dataset["Percent of freshmen receiving federal student loans"].fillna(dataset["Percent of freshmen receiving federal student loans"].median(), inplace=True)
dataset["Percent of freshmen receiving other loan aid"].fillna(dataset["Percent of freshmen receiving other loan aid"].median(), inplace=True)
dataset["Endowment assets (year end) per FTE enrollment (GASB)"].fillna(dataset["Endowment assets (year end) per FTE enrollment (GASB)"].median(), inplace=True)
dataset["Endowment assets (year end) per FTE enrollment (FASB)"].fillna(dataset["Endowment assets (year end) per FTE enrollment (FASB)"].median(), inplace=True)

In [117]:
dataset.columns

Index(['ID number', 'Name', 'year', 'ZIP code', 'Highest degree offered',
       'County name', 'Longitude location of institution',
       'Latitude location of institution', 'Religious affiliation',
       'Offers Less than one year certificate',
       ...
       'Percent of freshmen  receiving federal grant aid',
       'Percent of freshmen receiving Pell grants',
       'Percent of freshmen receiving other federal grant aid',
       'Percent of freshmen receiving state/local grant aid',
       'Percent of freshmen receiving institutional grant aid',
       'Percent of freshmen receiving student loan aid',
       'Percent of freshmen receiving federal student loans',
       'Percent of freshmen receiving other loan aid',
       'Endowment assets (year end) per FTE enrollment (GASB)',
       'Endowment assets (year end) per FTE enrollment (FASB)'],
      dtype='object', length=145)

In [118]:
X=dataset[['SAT Critical Reading 25th percentile score', 'SAT Critical Reading 75th percentile score', 'SAT Math 25th percentile score', 'SAT Math 75th percentile score','SAT Writing 25th percentile score','SAT Writing 75th percentile score','Control of institution']]
y=dataset['Percent of freshmen submitting SAT scores']

In [119]:
X=pd.get_dummies(X,[['Control of institution', 'County Name']]).astype(int)
X.head()

,SAT Critical Reading 25th percentile score,SAT Critical Reading 75th percentile score,SAT Math 25th percentile score,SAT Math 75th percentile score,SAT Writing 25th percentile score,SAT Writing 75th percentile score,"['Control of institution', 'County Name']_Private not-for-profit","['Control of institution', 'County Name']_Public"
0,370,450,350,450,450,566,0,1
1,520,640,520,650,450,566,0,1
2,460,570,470,580,450,566,1,0
3,510,640,510,650,450,566,0,1
4,380,480,370,480,450,566,0,1

In [120]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [121]:
mlr_model=LinearRegression()
mlr_model.fit(X_train.values, y_train)

LinearRegression()

In [122]:
print(mlr_model.coef_)

[ 0.21644442 -0.17268119  0.07508076 -0.09184296  0.1412916  -0.11801935
  0.56577975 -0.56577975]

In [123]:
print(mlr_model.intercept_)

74.81843192271711

In [124]:
y_pred_mlr=mlr_model.predict(X_test.values)

In [125]:
y_pred_mlr

array([46.73010293, 53.54605806, 55.32167469, 65.47835276, 61.04725015,
       55.69843539, 65.72723125, 55.32167469, 48.60177472, 56.77576254,
       54.19011518, 52.05919184, 63.59362478, 47.76430579, 53.76414286,
       55.69317026, 51.3000352 , 54.19011518, 27.90997503, 53.99528716,
       55.93437515, 52.97433608, 79.09748355, 50.58397342, 55.32167469,
       54.02685539, 50.57716933, 54.19011518, 61.33396292, 51.01650345,
       79.34555832, 55.32167469, 55.32167469, 55.32167469, 55.32167469,
       81.02632444, 54.32831171, 54.19011518, 58.50712363, 55.32167469,
       40.76041017, 55.80762535, 67.17411392, 56.71931832, 59.35249298,
       42.20932979, 22.29552954, 50.60583872, 57.88033908, 54.08171632,
       58.07725312, 58.53562832, 48.30437972, 55.32167469, 56.75054979,
       55.32167469, 60.29909888, 55.32167469, 63.41456522, 54.19011518,
       47.54537946, 56.94210715, 52.42997246, 48.5310573 , 58.56216862,
       68.09784306, 55.32167469, 61.45456732, 62.42578598, 55.32167469,
       55.32167469, 55.58214193, 55.32167469, 55.90435275, 58.79061662,
       54.19011518, 55.32167469, 54.26457683, 54.19011518, 55.32167469,
       55.32167469, 63.09023609, 52.30558836, 55.32167469, 53.83477101,
       60.25182612, 55.81453888, 47.87632124, 54.19011518, 57.14188501,
       53.98768156, 45.10279912, 57.10935817, 55.32167469, 54.56852429,
       47.40826752, 56.8353567 , 48.62970957, 61.9312575 , 54.19011518,
       55.59618236, 58.28009151, 64.72078459, 60.12699816, 54.19011518,
       55.32167469, 62.63179414, 51.74359388, 57.91790321, 52.13406985,
       54.19011518, 50.56285867, 61.43565467, 45.87569509, 54.13089202,
       60.49824023, 70.91448367, 54.19011518, 52.78491185, 61.4079657 ,
       51.27486341, 52.34719976, 45.46942419, 71.31231566, 57.35931909,
       54.19011518, 51.86640243, 46.09182525, 59.37820999, 55.32167469,
       52.96414991, 61.83669572, 55.32167469, 62.18456521, 69.15360035,
       49.56674769, 55.10689637, 50.82061434, 60.5535223 , 58.28779614,
       55.32167469, 47.69802077, 47.32028824, 61.69820934, 66.07507459,
       55.72597947, 47.13482112, 45.27423008, 52.83841555, 47.75610738,
       55.32167469, 51.052104  , 64.10294082, 54.19011518, 61.81229343,
       54.19011518, 50.86866037, 68.79380771, 55.66287593, 62.79717605,
       55.32167469, 51.70272614, 55.32167469, 55.32167469, 55.32167469,
       69.41277394, 84.83359658, 54.19011518, 46.38135312, 55.32167469,
       48.9988067 , 63.9147598 , 53.67650967, 55.70008379, 67.81204781,
       55.32167469, 71.52772219, 55.32167469, 54.19011518, 55.54263993,
       54.519303  , 56.82934606, 68.51828819, 38.67825766, 55.32167469,
       48.087582  , 59.42972852, 55.32167469, 48.84283163, 55.32167469,
       55.32167469, 47.08149476, 65.09406142, 60.9373999 , 50.54378487,
       61.07247097, 50.64158954, 59.1552276 , 51.4856505 , 44.89832876,
       54.19011518, 54.19011518, 52.53710902, 56.53252357, 71.16887956,
       55.32167469, 55.15170984, 60.64789615, 54.19011518, 53.37484703,
       55.32167469, 55.32167469, 55.32167469, 64.88182337, 52.36671327,
       55.32167469, 51.71084728, 48.65065905, 56.83058263, 48.30273132,
       64.75122691, 51.96479942, 62.17900667, 54.19011518, 62.63886405,
       57.64485379, 61.83610358, 61.48858585, 53.2568165 , 54.7033974 ,
       59.81812274, 55.38690848, 55.32167469, 56.13005701, 60.37230357,
       55.32167469, 52.6634389 , 52.47436602, 49.19454223, 52.77323763,
       63.56867589, 59.40937331, 56.76576066, 59.24899042, 58.64308025,
       55.32167469, 49.27203061, 60.35795857, 57.00696995, 61.01936779,
       63.41653936, 62.93796629, 40.45099406, 64.29139869, 55.32167469,
       52.94644341, 54.19011518, 77.66438763, 56.04819503, 58.89839416,
       55.65691873, 54.84289663, 55.32167469, 54.19011518, 45.32224576,
       53.78755672, 77.87421368, 55.32167469, 55.27340738, 55.32167469,
       81.43047758, 62.27142308, 54.19011518, 59.05877705, 59.96185442,
       59.25655473, 55.32167469, 53.4393076 , 57.82136292, 54.19011518,
       62.99535894, 66.63743407, 56.6529947 , 55.32167469, 53.37572221,
       65.37552066, 62.28185377, 67.52405914, 61.87274021, 55.32167469,
       48.08029396, 43.81993619, 54.19011518, 58.94456896, 55.32167469,
       40.41622805, 54.19011518, 55.32167469, 54.19011518, 55.32167469,
       54.19011518, 62.36014695, 55.32167469, 58.40454847, 56.07914533,
       59.81584226, 53.54770647])

In [126]:
mse=mean_squared_error(y_test, y_pred_mlr)
rmse= np.sqrt(mse)
r2=r2_score(y_test, y_pred_mlr)
print("Multiple Linear Regression Evaluation Metrics:")
print(f"Mean squared error, {mse:.2f}")
print(f"Root mean squared error, {rmse:.2f}")
print(f"R square, {r2:.2f}")

Multiple Linear Regression Evaluation Metrics:
Mean squared error, 930.80
Root mean squared error, 30.51
R square, 0.08